services:
  - type: web
    name: urb-web
    runtime: node
    region: oregon
    plan: free
    rootDir: .
    buildCommand: npm install -g pnpm && pnpm install --no-frozen-lockfile && pnpm --filter @urb/shared run prisma:dbpush && pnpm --filter @urb/shared run prisma:generate && pnpm --filter @urb/web run build
    startCommand: cd apps/web && npx next start -p $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: urb-db
          property: connectionString
      - key: NODE_ENV
        value: production

  - type: web
    name: urb-admin
    runtime: node
    region: oregon
    plan: free
    rootDir: .
    buildCommand: npm install -g pnpm && pnpm install --no-frozen-lockfile && pnpm --filter @urb/shared run prisma:dbpush && pnpm --filter @urb/shared run prisma:generate && pnpm --filter @urb/admin run build
    startCommand: cd apps/admin && npx next start -p $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: urb-db
          property: connectionString
      - key: NODE_ENV
        value: production

  - type: web
    name: urb-guia
    runtime: node
    region: oregon
    plan: free
    rootDir: .
    buildCommand: npm install -g pnpm && pnpm install --no-frozen-lockfile && pnpm --filter @urb/shared run prisma:dbpush && pnpm --filter @urb/shared run prisma:generate && pnpm --filter @urb/guia run build
    startCommand: cd apps/guia && npx next start -p $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: urb-db
          property: connectionString
      - key: NODE_ENV
        value: production
