// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/dashboard/admin" | "/dashboard/admin/planos" | "/dashboard/guia" | "/dashboard/guia/analytics" | "/dashboard/guia/atividades" | "/dashboard/guia/clientes" | "/dashboard/guia/pacotes" | "/dashboard/guia/pacotes/[id]" | "/dashboard/guia/perfil" | "/dashboard/guia/perfil/planos" | "/dashboard/guia/planos" | "/dashboard/guia/plugins" | "/dashboard/guia/plugins/[slug]" | "/dashboard/guia/plugins/docs" | "/dashboard/guia/prospector" | "/dashboard/guia/reservas" | "/dashboard/guia/roteiros" | "/dashboard/guia/roteiros/[id]" | "/guia/[id]" | "/login" | "/vip-customization"
type AppRouteHandlerRoutes = "/api/admin/guides" | "/api/admin/guides/[id]" | "/api/cron" | "/api/cron/auto-import" | "/api/payment/success" | "/api/places" | "/api/public/guides" | "/api/public/guides/featured" | "/api/public/packages" | "/api/public/packages/[id]" | "/api/public/reservations" | "/api/reservations" | "/api/reservations/[id]" | "/api/reservations/[id]/status" | "/api/result" | "/api/search"
type PageRoutes = never
type LayoutRoutes = "/" | "/dashboard/admin" | "/dashboard/guia"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/admin/guides": {}
  "/api/admin/guides/[id]": { "id": string; }
  "/api/cron": {}
  "/api/cron/auto-import": {}
  "/api/payment/success": {}
  "/api/places": {}
  "/api/public/guides": {}
  "/api/public/guides/featured": {}
  "/api/public/packages": {}
  "/api/public/packages/[id]": { "id": string; }
  "/api/public/reservations": {}
  "/api/reservations": {}
  "/api/reservations/[id]": { "id": string; }
  "/api/reservations/[id]/status": { "id": string; }
  "/api/result": {}
  "/api/search": {}
  "/dashboard/admin": {}
  "/dashboard/admin/planos": {}
  "/dashboard/guia": {}
  "/dashboard/guia/analytics": {}
  "/dashboard/guia/atividades": {}
  "/dashboard/guia/clientes": {}
  "/dashboard/guia/pacotes": {}
  "/dashboard/guia/pacotes/[id]": { "id": string; }
  "/dashboard/guia/perfil": {}
  "/dashboard/guia/perfil/planos": {}
  "/dashboard/guia/planos": {}
  "/dashboard/guia/plugins": {}
  "/dashboard/guia/plugins/[slug]": { "slug": string; }
  "/dashboard/guia/plugins/docs": {}
  "/dashboard/guia/prospector": {}
  "/dashboard/guia/reservas": {}
  "/dashboard/guia/roteiros": {}
  "/dashboard/guia/roteiros/[id]": { "id": string; }
  "/guia/[id]": { "id": string; }
  "/login": {}
  "/vip-customization": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/dashboard/admin": never
  "/dashboard/guia": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
