// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/dashboard/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin">> = Specific
  const handler = {} as typeof import("../../app/dashboard/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/admin/planos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/planos">> = Specific
  const handler = {} as typeof import("../../app/dashboard/admin/planos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/guia/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/guia/analytics">> = Specific
  const handler = {} as typeof import("../../app/dashboard/guia/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/guia/atividades/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/guia/atividades">> = Specific
  const handler = {} as typeof import("../../app/dashboard/guia/atividades/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/guia/clientes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/guia/clientes">> = Specific
  const handler = {} as typeof import("../../app/dashboard/guia/clientes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/guia/pacotes/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/guia/pacotes/[id]">> = Specific
  const handler = {} as typeof import("../../app/dashboard/guia/pacotes/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/guia/pacotes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/guia/pacotes">> = Specific
  const handler = {} as typeof import("../../app/dashboard/guia/pacotes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/guia/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/guia">> = Specific
  const handler = {} as typeof import("../../app/dashboard/guia/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/guia/perfil/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/guia/perfil">> = Specific
  const handler = {} as typeof import("../../app/dashboard/guia/perfil/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/guia/perfil/planos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/guia/perfil/planos">> = Specific
  const handler = {} as typeof import("../../app/dashboard/guia/perfil/planos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/guia/planos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/guia/planos">> = Specific
  const handler = {} as typeof import("../../app/dashboard/guia/planos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/guia/plugins/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/guia/plugins/[slug]">> = Specific
  const handler = {} as typeof import("../../app/dashboard/guia/plugins/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/guia/plugins/docs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/guia/plugins/docs">> = Specific
  const handler = {} as typeof import("../../app/dashboard/guia/plugins/docs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/guia/plugins/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/guia/plugins">> = Specific
  const handler = {} as typeof import("../../app/dashboard/guia/plugins/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/guia/prospector/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/guia/prospector">> = Specific
  const handler = {} as typeof import("../../app/dashboard/guia/prospector/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/guia/reservas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/guia/reservas">> = Specific
  const handler = {} as typeof import("../../app/dashboard/guia/reservas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/guia/roteiros/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/guia/roteiros/[id]">> = Specific
  const handler = {} as typeof import("../../app/dashboard/guia/roteiros/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/guia/roteiros/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/guia/roteiros">> = Specific
  const handler = {} as typeof import("../../app/dashboard/guia/roteiros/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/guia/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guia/[id]">> = Specific
  const handler = {} as typeof import("../../app/guia/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/vip-customization/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vip-customization">> = Specific
  const handler = {} as typeof import("../../app/vip-customization/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/guides/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/guides/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/admin/guides/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/guides/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/guides">> = Specific
  const handler = {} as typeof import("../../app/api/admin/guides/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cron/auto-import/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/auto-import">> = Specific
  const handler = {} as typeof import("../../app/api/cron/auto-import/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cron/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron">> = Specific
  const handler = {} as typeof import("../../app/api/cron/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/payment/success/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payment/success">> = Specific
  const handler = {} as typeof import("../../app/api/payment/success/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/places/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/places">> = Specific
  const handler = {} as typeof import("../../app/api/places/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/public/guides/featured/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/guides/featured">> = Specific
  const handler = {} as typeof import("../../app/api/public/guides/featured/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/public/guides/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/guides">> = Specific
  const handler = {} as typeof import("../../app/api/public/guides/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/public/packages/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/packages/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/public/packages/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/public/packages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/packages">> = Specific
  const handler = {} as typeof import("../../app/api/public/packages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/public/reservations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/reservations">> = Specific
  const handler = {} as typeof import("../../app/api/public/reservations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/reservations/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reservations/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/reservations/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/reservations/[id]/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reservations/[id]/status">> = Specific
  const handler = {} as typeof import("../../app/api/reservations/[id]/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/reservations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reservations">> = Specific
  const handler = {} as typeof import("../../app/api/reservations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/result/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/result">> = Specific
  const handler = {} as typeof import("../../app/api/result/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/search">> = Specific
  const handler = {} as typeof import("../../app/api/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/(main)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(main)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard/admin">> = Specific
  const handler = {} as typeof import("../../app/dashboard/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/guia/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard/guia">> = Specific
  const handler = {} as typeof import("../../app/dashboard/guia/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
