// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/add" | "/admin/assinaturas" | "/admin/cities" | "/admin/clients" | "/admin/cupons" | "/admin/edit/[id]" | "/admin/guias" | "/admin/import" | "/admin/places/[id]" | "/admin/planos" | "/admin/plugins" | "/admin/plugins/market" | "/admin/plugins/run/[slug]" | "/admin/prospects" | "/admin/reservas" | "/admin/settings/keys" | "/admin/settings/routes" | "/admin/settings/server" | "/admin/users" | "/admin/users/activity" | "/admin/users/admins" | "/guia/[id]" | "/login" | "/subscribe/[planId]" | "/subscribe/success"
type AppRouteHandlerRoutes = "/api/admin/cities" | "/api/admin/cities/featured" | "/api/admin/fix-locations" | "/api/admin/import-prospect" | "/api/admin/import-single" | "/api/admin/plugins" | "/api/admin/prospects" | "/api/admin/prospects/bulk" | "/api/admin/prospects/enrich" | "/api/admin/reimport-single" | "/api/admin/search-places" | "/api/admin/search-prospect" | "/api/checkout" | "/api/cron/auto-import" | "/api/debug-db" | "/api/external/plans"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/add": {}
  "/admin/assinaturas": {}
  "/admin/cities": {}
  "/admin/clients": {}
  "/admin/cupons": {}
  "/admin/edit/[id]": { "id": string; }
  "/admin/guias": {}
  "/admin/import": {}
  "/admin/places/[id]": { "id": string; }
  "/admin/planos": {}
  "/admin/plugins": {}
  "/admin/plugins/market": {}
  "/admin/plugins/run/[slug]": { "slug": string; }
  "/admin/prospects": {}
  "/admin/reservas": {}
  "/admin/settings/keys": {}
  "/admin/settings/routes": {}
  "/admin/settings/server": {}
  "/admin/users": {}
  "/admin/users/activity": {}
  "/admin/users/admins": {}
  "/api/admin/cities": {}
  "/api/admin/cities/featured": {}
  "/api/admin/fix-locations": {}
  "/api/admin/import-prospect": {}
  "/api/admin/import-single": {}
  "/api/admin/plugins": {}
  "/api/admin/prospects": {}
  "/api/admin/prospects/bulk": {}
  "/api/admin/prospects/enrich": {}
  "/api/admin/reimport-single": {}
  "/api/admin/search-places": {}
  "/api/admin/search-prospect": {}
  "/api/checkout": {}
  "/api/cron/auto-import": {}
  "/api/debug-db": {}
  "/api/external/plans": {}
  "/guia/[id]": { "id": string; }
  "/login": {}
  "/subscribe/[planId]": { "planId": string; }
  "/subscribe/success": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
