// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/admin/add/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/add">> = Specific
  const handler = {} as typeof import("../../app/admin/add/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/assinaturas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/assinaturas">> = Specific
  const handler = {} as typeof import("../../app/admin/assinaturas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/cities/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/cities">> = Specific
  const handler = {} as typeof import("../../app/admin/cities/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/clients/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/clients">> = Specific
  const handler = {} as typeof import("../../app/admin/clients/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/cupons/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/cupons">> = Specific
  const handler = {} as typeof import("../../app/admin/cupons/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/edit/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/edit/[id]">> = Specific
  const handler = {} as typeof import("../../app/admin/edit/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/guias/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/guias">> = Specific
  const handler = {} as typeof import("../../app/admin/guias/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/import/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/import">> = Specific
  const handler = {} as typeof import("../../app/admin/import/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/places/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/places/[id]">> = Specific
  const handler = {} as typeof import("../../app/admin/places/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/planos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/planos">> = Specific
  const handler = {} as typeof import("../../app/admin/planos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/plugins/market/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/plugins/market">> = Specific
  const handler = {} as typeof import("../../app/admin/plugins/market/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/plugins/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/plugins">> = Specific
  const handler = {} as typeof import("../../app/admin/plugins/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/plugins/run/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/plugins/run/[slug]">> = Specific
  const handler = {} as typeof import("../../app/admin/plugins/run/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/prospects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/prospects">> = Specific
  const handler = {} as typeof import("../../app/admin/prospects/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/reservas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/reservas">> = Specific
  const handler = {} as typeof import("../../app/admin/reservas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/settings/keys/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings/keys">> = Specific
  const handler = {} as typeof import("../../app/admin/settings/keys/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/settings/routes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings/routes">> = Specific
  const handler = {} as typeof import("../../app/admin/settings/routes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/settings/server/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings/server">> = Specific
  const handler = {} as typeof import("../../app/admin/settings/server/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/users/activity/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users/activity">> = Specific
  const handler = {} as typeof import("../../app/admin/users/activity/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/users/admins/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users/admins">> = Specific
  const handler = {} as typeof import("../../app/admin/users/admins/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../app/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/guia/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guia/[id]">> = Specific
  const handler = {} as typeof import("../../app/guia/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/subscribe/[planId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/subscribe/[planId]">> = Specific
  const handler = {} as typeof import("../../app/subscribe/[planId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/subscribe/success/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/subscribe/success">> = Specific
  const handler = {} as typeof import("../../app/subscribe/success/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/cities/featured/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/cities/featured">> = Specific
  const handler = {} as typeof import("../../app/api/admin/cities/featured/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/cities/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/cities">> = Specific
  const handler = {} as typeof import("../../app/api/admin/cities/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/fix-locations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/fix-locations">> = Specific
  const handler = {} as typeof import("../../app/api/admin/fix-locations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/import-prospect/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/import-prospect">> = Specific
  const handler = {} as typeof import("../../app/api/admin/import-prospect/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/import-single/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/import-single">> = Specific
  const handler = {} as typeof import("../../app/api/admin/import-single/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/plugins/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/plugins">> = Specific
  const handler = {} as typeof import("../../app/api/admin/plugins/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/prospects/bulk/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/prospects/bulk">> = Specific
  const handler = {} as typeof import("../../app/api/admin/prospects/bulk/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/prospects/enrich/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/prospects/enrich">> = Specific
  const handler = {} as typeof import("../../app/api/admin/prospects/enrich/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/prospects/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/prospects">> = Specific
  const handler = {} as typeof import("../../app/api/admin/prospects/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/reimport-single/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/reimport-single">> = Specific
  const handler = {} as typeof import("../../app/api/admin/reimport-single/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/search-places/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/search-places">> = Specific
  const handler = {} as typeof import("../../app/api/admin/search-places/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/search-prospect/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/search-prospect">> = Specific
  const handler = {} as typeof import("../../app/api/admin/search-prospect/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/checkout">> = Specific
  const handler = {} as typeof import("../../app/api/checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cron/auto-import/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/auto-import">> = Specific
  const handler = {} as typeof import("../../app/api/cron/auto-import/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/debug-db/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/debug-db">> = Specific
  const handler = {} as typeof import("../../app/api/debug-db/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/external/plans/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/external/plans">> = Specific
  const handler = {} as typeof import("../../app/api/external/plans/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
